from collections.abc import Mapping, Sequence
from pathlib import Path

from vitessce import VitessceConfig

from ._observations import _from_spatialdata, _from_split_sources


def imgbased_transcriptomics_from_spatialdata(
    sdata_path: str | Path,
    img_layer: str | None = None,
    labels_layer: str | None = None,
    table_layer: str | None = None,
    base_dir: str | Path | None = None,
    name: str = "Image-based transcriptomics",
    description: str = "Image-based transcriptomics",
    schema_version: str = "1.0.18",
    center: tuple[float, float] | None = None,
    zoom: float | None = -4,
    channels: Sequence[int | str] | None = None,
    palette: Sequence[str] | None = None,
    layer_opacity: float = 1.0,
    segmentation_color: str | None = None,
    segmentation_filled: bool = True,
    segmentation_stroke_width: float = 1.0,
    to_coordinate_system: str = "global",
    visualize_feature_matrix: bool = False,
    visualize_heatmap: bool = False,
    cluster_key: str | None = None,
    cluster_key_display_name: str = "Clusters",
    embedding_key: str | None = None,
    embedding_key_display_name: str = "UMAP",
) -> VitessceConfig:
    return _from_spatialdata(
        sdata_path=sdata_path,
        img_layer=img_layer,
        labels_layer=labels_layer,
        table_layer=table_layer,
        base_dir=base_dir,
        name=name,
        description=description,
        schema_version=schema_version,
        center=center,
        zoom=zoom,
        channels=channels,
        palette=palette,
        layer_opacity=layer_opacity,
        segmentation_color=segmentation_color,
        segmentation_filled=segmentation_filled,
        segmentation_stroke_width=segmentation_stroke_width,
        to_coordinate_system=to_coordinate_system,
        visualize_feature_matrix=visualize_feature_matrix,
        visualize_heatmap=visualize_heatmap,
        cluster_key=cluster_key,
        cluster_key_display_name=cluster_key_display_name,
        embedding_key=embedding_key,
        embedding_key_display_name=embedding_key_display_name,
        feature_type="gene",
    )


def imgbased_transcriptomics_from_split_sources(
    img_source: str | Path,
    labels_source: str | Path | None = None,
    adata_source: str | Path | None = None,
    adata_as_spots: bool = False,
    spot_radius_size_micron: int | None = None,
    base_dir: str | Path | None = None,
    name: str = "Image-based transcriptomics",
    description: str = "Image-based transcriptomics",
    schema_version: str = "1.0.18",
    center: tuple[float, float] | None = None,
    zoom: float | None = -4,
    channels: Sequence[int | str] | None = None,
    palette: Sequence[str] | None = None,
    layer_opacity: float = 1.0,
    segmentation_color: str | None = None,
    segmentation_filled: bool = True,
    segmentation_stroke_width: float = 1.0,
    microns_per_pixel_image: float | tuple[float, float] | None = None,
    coordinate_transformations_image: Sequence[Mapping[str, object]] | None = None,
    microns_per_pixel_mask: float | tuple[float, float] | None = None,
    coordinate_transformations_mask: Sequence[Mapping[str, object]] | None = None,
    visualize_feature_matrix: bool = False,
    visualize_heatmap: bool = False,
    spatial_key: str = "spatial",
    cluster_key: str | None = None,
    cluster_key_display_name: str = "Clusters",
    embedding_key: str | None = None,
    embedding_key_display_name: str = "UMAP",
) -> VitessceConfig:
    return _from_split_sources(
        img_source=img_source,
        labels_source=labels_source,
        adata_source=adata_source,
        adata_as_spots=adata_as_spots,
        spot_radius_size_micron=spot_radius_size_micron,
        base_dir=base_dir,
        name=name,
        description=description,
        schema_version=schema_version,
        center=center,
        zoom=zoom,
        channels=channels,
        palette=palette,
        layer_opacity=layer_opacity,
        segmentation_color=segmentation_color,
        segmentation_filled=segmentation_filled,
        segmentation_stroke_width=segmentation_stroke_width,
        microns_per_pixel_image=microns_per_pixel_image,
        coordinate_transformations_image=coordinate_transformations_image,
        microns_per_pixel_mask=microns_per_pixel_mask,
        coordinate_transformations_mask=coordinate_transformations_mask,
        visualize_feature_matrix=visualize_feature_matrix,
        visualize_heatmap=visualize_heatmap,
        spatial_key=spatial_key,
        cluster_key=cluster_key,
        cluster_key_display_name=cluster_key_display_name,
        embedding_key=embedding_key,
        embedding_key_display_name=embedding_key_display_name,
        feature_type="gene",
    )
